### ISSUE TITLE
Larger Test Error

### ISSUE THREAD

**Issue by LyazS** [bardiadoosti/HOPE#13]
Hi, I download the fhad dataset, make_data and run the code below:
```
$ python HOPE.py   --input_file ./datasets/fhad/   --test   --batch_size 16   --model_def HopeNet   --gpu   --gpu_number 0   --pretrained_model ./checkpoints/fhad/model-0.pkl
```
Then I get:
```
Test files loaded
HopeNet is loaded
Begin testing the network...
test error: 1609.94531
```
It is completely different to your paper. 
My torch==1.5.0, torchvision==0.6

**Comment by zclonely** [comment]
+1, and test error is more big  

`python HOPE.py --input_file ./datasets/ho/ --test --batch_size 64 --model_def HopeNet --gpu --gpu_number 0 --pretrained_model ./checkpoints/fhad/model-0.pkl`
`
Test files loaded       
  
HopeNet is loaded   
Begin testing the network...    
test error: 68022.01562
`
I don't know why...

**Comment by bardiadoosti** [comment]
> Hi, I download the fhad dataset, make_data and run the code below:
> 
> ```
> $ python HOPE.py   --input_file ./datasets/fhad/   --test   --batch_size 16   --model_def HopeNet   --gpu   --gpu_number 0   --pretrained_model ./checkpoints/fhad/model-0.pkl
> ```
> 
> Then I get:
> 
> ```
> Test files loaded
> HopeNet is loaded
> Begin testing the network...
> test error: 1609.94531
> ```
> 
> It is completely different to your paper.
> My torch==1.5.0, torchvision==0.6

Thanks for your comment.
I honestly don't know why your error is bigger than mine. I just cloned the code and ran the pretrained model and the loss is 267. (torch==1.4.0, torchvision==0.5)
Maybe `make_data.py` resulted something different.
Also, the number shown here is _loss_ not error mentioned in the paper.
Moreover, this is a ResNet50 model but the final results in the paper is from ResNet10.

**Comment by bardiadoosti** [comment]
> +1, and test error is more big
> 
> `python HOPE.py --input_file ./datasets/ho/ --test --batch_size 64 --model_def HopeNet --gpu --gpu_number 0 --pretrained_model ./checkpoints/fhad/model-0.pkl`
> `
> Test files loaded
> 
> HopeNet is loaded
> Begin testing the network...
> test error: 68022.01562
> `
> I don't know why...

In addition to the previous comments, the model is pretrained on fhad and you are testing it on HO.

**Comment by mslqing** [comment]
@bardiadoosti Hello, I changed line 12 of the hopenet.py file in the modules folder to Resnet10. But the following error occurred?

RuntimeError: size mismatch, m1: [464 x 514], m2: [2050 x 128] at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/THC/generic/THCTensorMathBlas.cu:290

Are there any other parameters that need to be modified? Hope for your reply. Thank you.
