### ISSUE TITLE
Help, about download fhad dataset

### ISSUE THREAD

**Issue by zclonely** [bardiadoosti/HOPE#14]
Can someone provide a download  Baidu Cloud link for the fhad dataset? 

I can not download fhad from [https://guiggh.github.io/publications/first-person-hands/](url)
Help~~
Thanks very much!

**Comment by bardiadoosti** [comment]
Hi,

As it is mentioned in the terms and conditions of the dataset we cannot redistribute the dataset on any server.

Terms and conditions:

The download and use of the dataset is released for academic research only and it is free to researchers from educational or research institutes for non-commercial purposes. When downloading the dataset you agree to (unless with expressed permission of the authors): not redistribute, modificate, or commercial usage of this dataset in any way or form, either partially or entirely.
