### ISSUE TITLE
A question about GraphNet.

### ISSUE THREAD

**Issue by ParanoidW** [bardiadoosti/HOPE#16]
I notice that the graph structure used in GraphNet and GraphUnet is identity matrix which means each node only connects itself. I wonder if there a misunderstanding here and I just want to know the reason.
Thank you.

**Comment by bardiadoosti** [comment]
They are _initialized_ with identity matrix. As it is mentioned in the paper (section 3.2.1) the graph convolution operation is adaptive and updates the the adjacency matrix (A) as well. Also as it is shown in the Table 3 of the paper, we got the best results initializing the adjacency matrix with identity matrix.
