### ISSUE TITLE
how to test with camera or with a image?

### ISSUE THREAD

**Issue by fuweifu-vtoo** [bardiadoosti/HOPE#3]
The dataset you mentioned in the readme is too large to download. I would like to ask if the author has a quick test method? How to test with rbg camera or a picture?
Thanks！

**Comment by bardiadoosti** [comment]
No we ran the code on the datasets mentioned in the paper. But if you have a small set of egocentric images (let's say 100) and want to run your code on them you can prepare the `images-test.npy` like:
```
np.array([/path/to/images/00.jpeg,
                  ...
          /path/to/images/99.jpeg]
```
and `points2d-test.npy` and `points3d-test.npy` like
```
np.zeros((100, 29, 2))
```
and
```
np.zeros((100, 29, 3))
```
and take a look at the outputs.
