### ISSUE TITLE
RuntimeError: invalid argument 7: expected 3D tensor at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:489

### ISSUE THREAD

**Issue by xmlmmfev** [bardiadoosti/HOPE#4]
I want to use it to test 2D image, but I got this error. What's the problem?
Code here:
```python
def predict(model, test_image_name):
    transform = image_transforms['test']
    image = Image.open(test_image_name)
    image = transform(image)
    if torch.cuda.is_available():
        image = image.cuda()
    image = image.view(1, *image.size())
    image = Variable(image)
    with torch.no_grad():
        model.eval()
        out = model(image)
        print(out)
        
predict(model, "./pic/100.JPG")
```

**Comment by bardiadoosti** [comment]
Not sure what the error is. Will you please provide some details about the line you got the error?
Also make sure the size of the input tensor is `torch.Size([1, 3, 224, 224])`.

**Comment by bardiadoosti** [comment]
Also let me know what PyTorch version you are using.

**Comment by xmlmmfev** [comment]
Thank you for helping me.
my input tensor:
![image](https://user-images.githubusercontent.com/14361955/79229829-39e93380-7e96-11ea-9ae7-d7d0ea9acfa2.png)

and my torch version
![image](https://user-images.githubusercontent.com/14361955/79229878-508f8a80-7e96-11ea-8944-08d5339fb333.png)

**Comment by bardiadoosti** [comment]
Ok try running the model (not the pretrained one) without CUDA and see if it runs. If yes there should be some conflict between the PyTorch and CUDA versions. I am using pytorch 1.4.0 and cuda 10.1.
