### ISSUE TITLE
How can I get a model that just estimate keypoint of hand

### ISSUE THREAD

**Issue by macqueen09** [bardiadoosti/HOPE#9]
your model is very effective.
I want get a hand pose net run in laptop or mobilephone which can get a position of hand keypoint. 
So how can I seperate your hand pose estimate model to make my app.
(My code ability isn't particularly strong )
I already has a detection model to find specify hand gesture , but I still want a fast hand pose estimate model. 
Thank you

**Comment by bardiadoosti** [comment]
Not quite sure about that, but I think you have to use PyTorch Mobile interface https://pytorch.org/mobile/home/
